// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoviesApis.DBContexts;

namespace MoviesApis.Migrations
{
    [DbContext(typeof(MySqlDbContext))]
    [Migration("20210608074742_UsersTableMigration")]
    partial class UsersTableMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("MoviesApis.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastUpdateDateTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDateTime = new DateTime(2021, 2, 23, 20, 6, 46, 579, DateTimeKind.Local).AddTicks(3755),
                            FirstName = "Kenna",
                            LastName = "Prohaska"
                        },
                        new
                        {
                            Id = 2,
                            CreationDateTime = new DateTime(2021, 4, 21, 22, 12, 16, 568, DateTimeKind.Local).AddTicks(6106),
                            FirstName = "Jerrell",
                            LastName = "Rogahn"
                        },
                        new
                        {
                            Id = 3,
                            CreationDateTime = new DateTime(2021, 1, 10, 22, 52, 21, 751, DateTimeKind.Local).AddTicks(3868),
                            FirstName = "Melany",
                            LastName = "Upton"
                        },
                        new
                        {
                            Id = 4,
                            CreationDateTime = new DateTime(2021, 4, 29, 4, 9, 49, 202, DateTimeKind.Local).AddTicks(2576),
                            FirstName = "Jameson",
                            LastName = "Hermann"
                        },
                        new
                        {
                            Id = 5,
                            CreationDateTime = new DateTime(2020, 8, 18, 8, 27, 50, 561, DateTimeKind.Local).AddTicks(1835),
                            FirstName = "Anita",
                            LastName = "Nitzsche"
                        },
                        new
                        {
                            Id = 6,
                            CreationDateTime = new DateTime(2020, 12, 30, 6, 40, 54, 60, DateTimeKind.Local).AddTicks(3589),
                            FirstName = "Louisa",
                            LastName = "Hackett"
                        },
                        new
                        {
                            Id = 7,
                            CreationDateTime = new DateTime(2020, 7, 30, 8, 20, 39, 714, DateTimeKind.Local).AddTicks(9215),
                            FirstName = "Tracy",
                            LastName = "Heidenreich"
                        },
                        new
                        {
                            Id = 8,
                            CreationDateTime = new DateTime(2021, 2, 16, 6, 7, 33, 724, DateTimeKind.Local).AddTicks(7618),
                            FirstName = "Horacio",
                            LastName = "Kulas"
                        },
                        new
                        {
                            Id = 9,
                            CreationDateTime = new DateTime(2020, 12, 1, 15, 56, 20, 991, DateTimeKind.Local).AddTicks(9842),
                            FirstName = "Orlo",
                            LastName = "Bradtke"
                        },
                        new
                        {
                            Id = 10,
                            CreationDateTime = new DateTime(2021, 4, 20, 6, 47, 0, 183, DateTimeKind.Local).AddTicks(8273),
                            FirstName = "Leif",
                            LastName = "Schmidt"
                        },
                        new
                        {
                            Id = 11,
                            CreationDateTime = new DateTime(2020, 12, 6, 18, 36, 11, 809, DateTimeKind.Local).AddTicks(4133),
                            FirstName = "Roselyn",
                            LastName = "Rowe"
                        },
                        new
                        {
                            Id = 12,
                            CreationDateTime = new DateTime(2020, 12, 12, 16, 55, 11, 813, DateTimeKind.Local).AddTicks(6357),
                            FirstName = "Gilberto",
                            LastName = "Ebert"
                        },
                        new
                        {
                            Id = 13,
                            CreationDateTime = new DateTime(2020, 12, 8, 8, 45, 2, 567, DateTimeKind.Local).AddTicks(9108),
                            FirstName = "Emmie",
                            LastName = "Kutch"
                        },
                        new
                        {
                            Id = 14,
                            CreationDateTime = new DateTime(2020, 7, 16, 10, 14, 6, 987, DateTimeKind.Local).AddTicks(1260),
                            FirstName = "Antonia",
                            LastName = "Mitchell"
                        },
                        new
                        {
                            Id = 15,
                            CreationDateTime = new DateTime(2020, 7, 7, 7, 36, 34, 993, DateTimeKind.Local).AddTicks(2494),
                            FirstName = "Cecil",
                            LastName = "Strosin"
                        },
                        new
                        {
                            Id = 16,
                            CreationDateTime = new DateTime(2020, 10, 6, 21, 17, 23, 960, DateTimeKind.Local).AddTicks(4238),
                            FirstName = "Cortney",
                            LastName = "Schamberger"
                        },
                        new
                        {
                            Id = 17,
                            CreationDateTime = new DateTime(2020, 10, 22, 13, 9, 21, 640, DateTimeKind.Local).AddTicks(5843),
                            FirstName = "Seamus",
                            LastName = "Jerde"
                        },
                        new
                        {
                            Id = 18,
                            CreationDateTime = new DateTime(2020, 11, 26, 22, 20, 19, 235, DateTimeKind.Local).AddTicks(3848),
                            FirstName = "Halie",
                            LastName = "Frami"
                        },
                        new
                        {
                            Id = 19,
                            CreationDateTime = new DateTime(2021, 3, 23, 18, 0, 34, 893, DateTimeKind.Local).AddTicks(2797),
                            FirstName = "Lelah",
                            LastName = "Cole"
                        },
                        new
                        {
                            Id = 20,
                            CreationDateTime = new DateTime(2020, 10, 15, 11, 39, 14, 983, DateTimeKind.Local).AddTicks(6974),
                            FirstName = "Wilfredo",
                            LastName = "Raynor"
                        },
                        new
                        {
                            Id = 21,
                            CreationDateTime = new DateTime(2021, 4, 30, 0, 13, 46, 987, DateTimeKind.Local).AddTicks(7298),
                            FirstName = "Lesley",
                            LastName = "Brakus"
                        },
                        new
                        {
                            Id = 22,
                            CreationDateTime = new DateTime(2020, 11, 3, 18, 10, 51, 692, DateTimeKind.Local).AddTicks(9971),
                            FirstName = "Donnie",
                            LastName = "Mosciski"
                        },
                        new
                        {
                            Id = 23,
                            CreationDateTime = new DateTime(2021, 1, 2, 9, 52, 1, 951, DateTimeKind.Local).AddTicks(2815),
                            FirstName = "Lennie",
                            LastName = "Padberg"
                        },
                        new
                        {
                            Id = 24,
                            CreationDateTime = new DateTime(2020, 8, 17, 15, 3, 38, 338, DateTimeKind.Local).AddTicks(9582),
                            FirstName = "Emma",
                            LastName = "Halvorson"
                        },
                        new
                        {
                            Id = 25,
                            CreationDateTime = new DateTime(2020, 9, 10, 0, 22, 46, 578, DateTimeKind.Local).AddTicks(8143),
                            FirstName = "Trisha",
                            LastName = "Stracke"
                        },
                        new
                        {
                            Id = 26,
                            CreationDateTime = new DateTime(2020, 10, 24, 15, 0, 42, 790, DateTimeKind.Local).AddTicks(4865),
                            FirstName = "Vidal",
                            LastName = "Gislason"
                        },
                        new
                        {
                            Id = 27,
                            CreationDateTime = new DateTime(2021, 2, 15, 7, 46, 4, 384, DateTimeKind.Local).AddTicks(8334),
                            FirstName = "Gerson",
                            LastName = "Mante"
                        },
                        new
                        {
                            Id = 28,
                            CreationDateTime = new DateTime(2021, 1, 18, 7, 41, 59, 430, DateTimeKind.Local).AddTicks(8626),
                            FirstName = "Roselyn",
                            LastName = "Rempel"
                        },
                        new
                        {
                            Id = 29,
                            CreationDateTime = new DateTime(2020, 12, 2, 6, 14, 8, 165, DateTimeKind.Local).AddTicks(3072),
                            FirstName = "Joelle",
                            LastName = "Kertzmann"
                        },
                        new
                        {
                            Id = 30,
                            CreationDateTime = new DateTime(2021, 5, 10, 7, 53, 9, 200, DateTimeKind.Local).AddTicks(3572),
                            FirstName = "Watson",
                            LastName = "Sawayn"
                        },
                        new
                        {
                            Id = 31,
                            CreationDateTime = new DateTime(2020, 8, 27, 2, 9, 56, 297, DateTimeKind.Local).AddTicks(2403),
                            FirstName = "Doyle",
                            LastName = "Heaney"
                        },
                        new
                        {
                            Id = 32,
                            CreationDateTime = new DateTime(2020, 12, 7, 23, 5, 51, 892, DateTimeKind.Local).AddTicks(8089),
                            FirstName = "Royal",
                            LastName = "Koch"
                        },
                        new
                        {
                            Id = 33,
                            CreationDateTime = new DateTime(2021, 3, 8, 17, 53, 4, 393, DateTimeKind.Local).AddTicks(285),
                            FirstName = "Parker",
                            LastName = "Treutel"
                        },
                        new
                        {
                            Id = 34,
                            CreationDateTime = new DateTime(2021, 4, 27, 15, 48, 33, 497, DateTimeKind.Local).AddTicks(3188),
                            FirstName = "Erik",
                            LastName = "Mitchell"
                        },
                        new
                        {
                            Id = 35,
                            CreationDateTime = new DateTime(2021, 5, 3, 17, 38, 52, 39, DateTimeKind.Local).AddTicks(2961),
                            FirstName = "Dax",
                            LastName = "Lynch"
                        },
                        new
                        {
                            Id = 36,
                            CreationDateTime = new DateTime(2021, 1, 20, 3, 26, 12, 528, DateTimeKind.Local).AddTicks(309),
                            FirstName = "Reece",
                            LastName = "Kovacek"
                        },
                        new
                        {
                            Id = 37,
                            CreationDateTime = new DateTime(2020, 7, 26, 20, 23, 28, 49, DateTimeKind.Local).AddTicks(3848),
                            FirstName = "Pamela",
                            LastName = "Nolan"
                        },
                        new
                        {
                            Id = 38,
                            CreationDateTime = new DateTime(2021, 4, 14, 19, 23, 11, 252, DateTimeKind.Local).AddTicks(1043),
                            FirstName = "Lafayette",
                            LastName = "Medhurst"
                        },
                        new
                        {
                            Id = 39,
                            CreationDateTime = new DateTime(2021, 1, 22, 19, 33, 1, 210, DateTimeKind.Local).AddTicks(6442),
                            FirstName = "Ethelyn",
                            LastName = "Runolfsson"
                        },
                        new
                        {
                            Id = 40,
                            CreationDateTime = new DateTime(2021, 4, 3, 2, 48, 5, 891, DateTimeKind.Local).AddTicks(4345),
                            FirstName = "Miracle",
                            LastName = "Runolfsdottir"
                        },
                        new
                        {
                            Id = 41,
                            CreationDateTime = new DateTime(2020, 7, 17, 18, 6, 48, 899, DateTimeKind.Local).AddTicks(6532),
                            FirstName = "Arianna",
                            LastName = "Nader"
                        },
                        new
                        {
                            Id = 42,
                            CreationDateTime = new DateTime(2020, 6, 17, 16, 47, 0, 563, DateTimeKind.Local).AddTicks(7256),
                            FirstName = "Felicia",
                            LastName = "Bauch"
                        },
                        new
                        {
                            Id = 43,
                            CreationDateTime = new DateTime(2021, 1, 11, 17, 41, 36, 882, DateTimeKind.Local).AddTicks(4696),
                            FirstName = "Alden",
                            LastName = "Bogisich"
                        },
                        new
                        {
                            Id = 44,
                            CreationDateTime = new DateTime(2021, 1, 25, 20, 27, 38, 20, DateTimeKind.Local).AddTicks(2383),
                            FirstName = "Dedrick",
                            LastName = "Daniel"
                        },
                        new
                        {
                            Id = 45,
                            CreationDateTime = new DateTime(2020, 6, 21, 12, 58, 31, 875, DateTimeKind.Local).AddTicks(9399),
                            FirstName = "Furman",
                            LastName = "Beier"
                        },
                        new
                        {
                            Id = 46,
                            CreationDateTime = new DateTime(2021, 4, 6, 7, 10, 10, 462, DateTimeKind.Local).AddTicks(5268),
                            FirstName = "Cleta",
                            LastName = "Mohr"
                        },
                        new
                        {
                            Id = 47,
                            CreationDateTime = new DateTime(2020, 6, 20, 12, 35, 5, 966, DateTimeKind.Local).AddTicks(7361),
                            FirstName = "Edwina",
                            LastName = "Pfeffer"
                        },
                        new
                        {
                            Id = 48,
                            CreationDateTime = new DateTime(2021, 4, 18, 5, 29, 37, 560, DateTimeKind.Local).AddTicks(717),
                            FirstName = "Brett",
                            LastName = "Dibbert"
                        },
                        new
                        {
                            Id = 49,
                            CreationDateTime = new DateTime(2020, 9, 8, 3, 55, 34, 338, DateTimeKind.Local).AddTicks(5774),
                            FirstName = "Coy",
                            LastName = "Pfeffer"
                        },
                        new
                        {
                            Id = 50,
                            CreationDateTime = new DateTime(2020, 9, 28, 14, 8, 1, 219, DateTimeKind.Local).AddTicks(9468),
                            FirstName = "Lonny",
                            LastName = "Larkin"
                        },
                        new
                        {
                            Id = 51,
                            CreationDateTime = new DateTime(2021, 4, 20, 19, 27, 50, 826, DateTimeKind.Local).AddTicks(2721),
                            FirstName = "Brain",
                            LastName = "Bergstrom"
                        },
                        new
                        {
                            Id = 52,
                            CreationDateTime = new DateTime(2020, 6, 19, 12, 51, 16, 252, DateTimeKind.Local).AddTicks(6502),
                            FirstName = "Ansley",
                            LastName = "Friesen"
                        },
                        new
                        {
                            Id = 53,
                            CreationDateTime = new DateTime(2020, 12, 2, 19, 16, 18, 922, DateTimeKind.Local).AddTicks(818),
                            FirstName = "Dameon",
                            LastName = "Towne"
                        },
                        new
                        {
                            Id = 54,
                            CreationDateTime = new DateTime(2021, 1, 19, 20, 1, 17, 420, DateTimeKind.Local).AddTicks(1815),
                            FirstName = "Brad",
                            LastName = "Schimmel"
                        },
                        new
                        {
                            Id = 55,
                            CreationDateTime = new DateTime(2020, 12, 19, 4, 18, 16, 545, DateTimeKind.Local).AddTicks(6822),
                            FirstName = "Whitney",
                            LastName = "Littel"
                        },
                        new
                        {
                            Id = 56,
                            CreationDateTime = new DateTime(2020, 11, 25, 17, 10, 41, 193, DateTimeKind.Local).AddTicks(6658),
                            FirstName = "Jewel",
                            LastName = "Erdman"
                        },
                        new
                        {
                            Id = 57,
                            CreationDateTime = new DateTime(2021, 4, 11, 15, 11, 6, 23, DateTimeKind.Local).AddTicks(8119),
                            FirstName = "Christopher",
                            LastName = "Connelly"
                        },
                        new
                        {
                            Id = 58,
                            CreationDateTime = new DateTime(2021, 5, 11, 13, 43, 30, 283, DateTimeKind.Local).AddTicks(8613),
                            FirstName = "Colleen",
                            LastName = "Kemmer"
                        },
                        new
                        {
                            Id = 59,
                            CreationDateTime = new DateTime(2020, 12, 27, 1, 47, 7, 402, DateTimeKind.Local).AddTicks(5202),
                            FirstName = "Cristobal",
                            LastName = "Welch"
                        },
                        new
                        {
                            Id = 60,
                            CreationDateTime = new DateTime(2021, 1, 30, 7, 30, 59, 510, DateTimeKind.Local).AddTicks(7785),
                            FirstName = "Newton",
                            LastName = "Conn"
                        },
                        new
                        {
                            Id = 61,
                            CreationDateTime = new DateTime(2020, 11, 11, 18, 25, 9, 424, DateTimeKind.Local).AddTicks(362),
                            FirstName = "Danial",
                            LastName = "Huels"
                        },
                        new
                        {
                            Id = 62,
                            CreationDateTime = new DateTime(2021, 4, 30, 5, 25, 22, 787, DateTimeKind.Local).AddTicks(225),
                            FirstName = "Merlin",
                            LastName = "Carroll"
                        },
                        new
                        {
                            Id = 63,
                            CreationDateTime = new DateTime(2020, 8, 16, 18, 23, 58, 159, DateTimeKind.Local).AddTicks(8511),
                            FirstName = "Darlene",
                            LastName = "Gutkowski"
                        },
                        new
                        {
                            Id = 64,
                            CreationDateTime = new DateTime(2020, 9, 19, 8, 34, 48, 265, DateTimeKind.Local).AddTicks(3557),
                            FirstName = "Zane",
                            LastName = "Wiza"
                        },
                        new
                        {
                            Id = 65,
                            CreationDateTime = new DateTime(2020, 7, 16, 21, 7, 36, 482, DateTimeKind.Local).AddTicks(8661),
                            FirstName = "Mafalda",
                            LastName = "Cummerata"
                        },
                        new
                        {
                            Id = 66,
                            CreationDateTime = new DateTime(2020, 10, 16, 12, 25, 24, 448, DateTimeKind.Local).AddTicks(520),
                            FirstName = "Krystina",
                            LastName = "Crona"
                        },
                        new
                        {
                            Id = 67,
                            CreationDateTime = new DateTime(2020, 12, 19, 0, 50, 13, 613, DateTimeKind.Local).AddTicks(4028),
                            FirstName = "Marcos",
                            LastName = "Rath"
                        },
                        new
                        {
                            Id = 68,
                            CreationDateTime = new DateTime(2021, 1, 22, 16, 4, 39, 775, DateTimeKind.Local).AddTicks(1770),
                            FirstName = "Cruz",
                            LastName = "King"
                        },
                        new
                        {
                            Id = 69,
                            CreationDateTime = new DateTime(2020, 10, 20, 1, 47, 34, 778, DateTimeKind.Local).AddTicks(4076),
                            FirstName = "Kaden",
                            LastName = "Walsh"
                        },
                        new
                        {
                            Id = 70,
                            CreationDateTime = new DateTime(2021, 2, 17, 3, 7, 54, 383, DateTimeKind.Local).AddTicks(3297),
                            FirstName = "Anais",
                            LastName = "Steuber"
                        },
                        new
                        {
                            Id = 71,
                            CreationDateTime = new DateTime(2020, 9, 7, 5, 45, 0, 159, DateTimeKind.Local).AddTicks(4476),
                            FirstName = "Jovany",
                            LastName = "Kovacek"
                        },
                        new
                        {
                            Id = 72,
                            CreationDateTime = new DateTime(2021, 1, 13, 13, 52, 46, 764, DateTimeKind.Local).AddTicks(5090),
                            FirstName = "Carole",
                            LastName = "Treutel"
                        },
                        new
                        {
                            Id = 73,
                            CreationDateTime = new DateTime(2021, 1, 4, 9, 44, 16, 467, DateTimeKind.Local).AddTicks(9086),
                            FirstName = "Ramona",
                            LastName = "Gleason"
                        },
                        new
                        {
                            Id = 74,
                            CreationDateTime = new DateTime(2020, 7, 8, 10, 37, 16, 310, DateTimeKind.Local).AddTicks(6518),
                            FirstName = "Francesca",
                            LastName = "Glover"
                        },
                        new
                        {
                            Id = 75,
                            CreationDateTime = new DateTime(2021, 4, 8, 4, 27, 35, 922, DateTimeKind.Local).AddTicks(6857),
                            FirstName = "Mitchel",
                            LastName = "Dicki"
                        },
                        new
                        {
                            Id = 76,
                            CreationDateTime = new DateTime(2021, 3, 3, 0, 5, 6, 750, DateTimeKind.Local).AddTicks(4903),
                            FirstName = "Ignacio",
                            LastName = "Littel"
                        },
                        new
                        {
                            Id = 77,
                            CreationDateTime = new DateTime(2020, 8, 25, 2, 53, 10, 399, DateTimeKind.Local).AddTicks(8859),
                            FirstName = "Cheyenne",
                            LastName = "Murray"
                        },
                        new
                        {
                            Id = 78,
                            CreationDateTime = new DateTime(2021, 1, 3, 13, 43, 2, 979, DateTimeKind.Local).AddTicks(3149),
                            FirstName = "Queenie",
                            LastName = "Bode"
                        },
                        new
                        {
                            Id = 79,
                            CreationDateTime = new DateTime(2020, 6, 27, 16, 32, 33, 828, DateTimeKind.Local).AddTicks(8009),
                            FirstName = "Shawna",
                            LastName = "Anderson"
                        },
                        new
                        {
                            Id = 80,
                            CreationDateTime = new DateTime(2021, 3, 29, 17, 21, 46, 570, DateTimeKind.Local).AddTicks(9854),
                            FirstName = "Clifton",
                            LastName = "Dare"
                        },
                        new
                        {
                            Id = 81,
                            CreationDateTime = new DateTime(2020, 12, 27, 15, 58, 23, 820, DateTimeKind.Local).AddTicks(1675),
                            FirstName = "Jaqueline",
                            LastName = "Dare"
                        },
                        new
                        {
                            Id = 82,
                            CreationDateTime = new DateTime(2020, 12, 6, 19, 58, 55, 532, DateTimeKind.Local).AddTicks(9655),
                            FirstName = "Joanny",
                            LastName = "Kozey"
                        },
                        new
                        {
                            Id = 83,
                            CreationDateTime = new DateTime(2021, 3, 2, 11, 58, 33, 166, DateTimeKind.Local).AddTicks(7769),
                            FirstName = "Vito",
                            LastName = "Kuphal"
                        },
                        new
                        {
                            Id = 84,
                            CreationDateTime = new DateTime(2020, 7, 17, 21, 40, 2, 509, DateTimeKind.Local).AddTicks(8807),
                            FirstName = "Jermey",
                            LastName = "Rutherford"
                        },
                        new
                        {
                            Id = 85,
                            CreationDateTime = new DateTime(2020, 12, 28, 23, 25, 30, 787, DateTimeKind.Local).AddTicks(8515),
                            FirstName = "Dahlia",
                            LastName = "Hagenes"
                        },
                        new
                        {
                            Id = 86,
                            CreationDateTime = new DateTime(2021, 3, 7, 4, 52, 24, 417, DateTimeKind.Local).AddTicks(3045),
                            FirstName = "Katlynn",
                            LastName = "Kulas"
                        },
                        new
                        {
                            Id = 87,
                            CreationDateTime = new DateTime(2021, 1, 20, 1, 28, 43, 227, DateTimeKind.Local).AddTicks(5838),
                            FirstName = "Coralie",
                            LastName = "Botsford"
                        },
                        new
                        {
                            Id = 88,
                            CreationDateTime = new DateTime(2021, 3, 18, 14, 0, 29, 699, DateTimeKind.Local).AddTicks(9451),
                            FirstName = "Frederique",
                            LastName = "Swift"
                        },
                        new
                        {
                            Id = 89,
                            CreationDateTime = new DateTime(2021, 1, 17, 8, 26, 25, 434, DateTimeKind.Local).AddTicks(857),
                            FirstName = "Joseph",
                            LastName = "Raynor"
                        },
                        new
                        {
                            Id = 90,
                            CreationDateTime = new DateTime(2020, 7, 19, 20, 41, 34, 671, DateTimeKind.Local).AddTicks(3807),
                            FirstName = "Enrique",
                            LastName = "Gorczany"
                        },
                        new
                        {
                            Id = 91,
                            CreationDateTime = new DateTime(2021, 5, 7, 12, 22, 2, 17, DateTimeKind.Local).AddTicks(8482),
                            FirstName = "Izabella",
                            LastName = "Morar"
                        },
                        new
                        {
                            Id = 92,
                            CreationDateTime = new DateTime(2021, 5, 5, 14, 28, 18, 684, DateTimeKind.Local).AddTicks(8238),
                            FirstName = "Dariana",
                            LastName = "Towne"
                        },
                        new
                        {
                            Id = 93,
                            CreationDateTime = new DateTime(2020, 9, 19, 4, 1, 59, 480, DateTimeKind.Local).AddTicks(9145),
                            FirstName = "Janiya",
                            LastName = "Erdman"
                        },
                        new
                        {
                            Id = 94,
                            CreationDateTime = new DateTime(2021, 5, 23, 11, 8, 9, 579, DateTimeKind.Local).AddTicks(7317),
                            FirstName = "Mallie",
                            LastName = "Kozey"
                        },
                        new
                        {
                            Id = 95,
                            CreationDateTime = new DateTime(2020, 7, 30, 17, 29, 13, 328, DateTimeKind.Local).AddTicks(9544),
                            FirstName = "Zoie",
                            LastName = "Pfannerstill"
                        },
                        new
                        {
                            Id = 96,
                            CreationDateTime = new DateTime(2020, 8, 30, 19, 55, 5, 570, DateTimeKind.Local).AddTicks(6847),
                            FirstName = "Sonia",
                            LastName = "McDermott"
                        },
                        new
                        {
                            Id = 97,
                            CreationDateTime = new DateTime(2020, 12, 1, 0, 56, 5, 470, DateTimeKind.Local).AddTicks(3632),
                            FirstName = "Winfield",
                            LastName = "Hartmann"
                        },
                        new
                        {
                            Id = 98,
                            CreationDateTime = new DateTime(2021, 5, 8, 23, 3, 45, 529, DateTimeKind.Local).AddTicks(9330),
                            FirstName = "Mathew",
                            LastName = "Zboncak"
                        },
                        new
                        {
                            Id = 99,
                            CreationDateTime = new DateTime(2021, 2, 18, 16, 54, 42, 411, DateTimeKind.Local).AddTicks(3653),
                            FirstName = "Randi",
                            LastName = "Breitenberg"
                        },
                        new
                        {
                            Id = 100,
                            CreationDateTime = new DateTime(2020, 9, 6, 2, 8, 23, 378, DateTimeKind.Local).AddTicks(7258),
                            FirstName = "Dalton",
                            LastName = "Yundt"
                        });
                });

            modelBuilder.Entity("MoviesApis.Models.WatchList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastUpdateDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SeekPosition")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VideoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WatchList");
                });

            modelBuilder.Entity("MoviesApis.Models.WatchList", b =>
                {
                    b.HasOne("MoviesApis.Models.User", null)
                        .WithMany("WatchHistory")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MoviesApis.Models.User", b =>
                {
                    b.Navigation("WatchHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
