// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoviesApis.DBContexts;

namespace MoviesApis.Migrations
{
    [DbContext(typeof(MySqlDbContext))]
    [Migration("20210609084921_SeedSeasons")]
    partial class SeedSeasons
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("MoviesApis.Models.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EposidesNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdateDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SeriesId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.ToTable("Seasons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDateTime = new DateTime(2020, 8, 13, 14, 45, 33, 975, DateTimeKind.Local).AddTicks(7066),
                            EposidesNumber = 6,
                            SeriesId = 556,
                            Title = "Buckinghamshire Buckinghamshire Metal invoice"
                        },
                        new
                        {
                            Id = 2,
                            CreationDateTime = new DateTime(2020, 7, 30, 23, 54, 59, 14, DateTimeKind.Local).AddTicks(6522),
                            EposidesNumber = 6,
                            SeriesId = 288,
                            Title = "Dynamic Forward Mission Field"
                        },
                        new
                        {
                            Id = 3,
                            CreationDateTime = new DateTime(2020, 8, 25, 14, 30, 52, 18, DateTimeKind.Local).AddTicks(6317),
                            EposidesNumber = 6,
                            SeriesId = 301,
                            Title = "SSL throughput red Unbranded"
                        },
                        new
                        {
                            Id = 4,
                            CreationDateTime = new DateTime(2020, 7, 13, 22, 25, 39, 562, DateTimeKind.Local).AddTicks(3398),
                            EposidesNumber = 6,
                            SeriesId = 782,
                            Title = "Plastic withdrawal clear-thinking Gorgeous"
                        },
                        new
                        {
                            Id = 5,
                            CreationDateTime = new DateTime(2021, 3, 3, 21, 4, 39, 648, DateTimeKind.Local).AddTicks(5436),
                            EposidesNumber = 6,
                            SeriesId = 128,
                            Title = "Oregon generating 24 hour visualize"
                        },
                        new
                        {
                            Id = 6,
                            CreationDateTime = new DateTime(2020, 9, 9, 12, 37, 22, 385, DateTimeKind.Local).AddTicks(1484),
                            EposidesNumber = 6,
                            SeriesId = 624,
                            Title = "Plastic Awesome Soft Ball mesh Course"
                        },
                        new
                        {
                            Id = 7,
                            CreationDateTime = new DateTime(2021, 4, 5, 3, 31, 7, 590, DateTimeKind.Local).AddTicks(9396),
                            EposidesNumber = 6,
                            SeriesId = 409,
                            Title = "Buckinghamshire Malaysian Ringgit New Hampshire Jersey"
                        },
                        new
                        {
                            Id = 8,
                            CreationDateTime = new DateTime(2021, 1, 19, 4, 12, 31, 412, DateTimeKind.Local),
                            EposidesNumber = 6,
                            SeriesId = 641,
                            Title = "Isle capability repurpose deposit"
                        },
                        new
                        {
                            Id = 9,
                            CreationDateTime = new DateTime(2020, 11, 19, 9, 34, 25, 869, DateTimeKind.Local).AddTicks(5028),
                            EposidesNumber = 6,
                            SeriesId = 803,
                            Title = "back up invoice asymmetric Branch"
                        },
                        new
                        {
                            Id = 10,
                            CreationDateTime = new DateTime(2020, 8, 20, 16, 57, 11, 580, DateTimeKind.Local).AddTicks(3913),
                            EposidesNumber = 6,
                            SeriesId = 443,
                            Title = "Serbian Dinar regional Centralized International"
                        },
                        new
                        {
                            Id = 11,
                            CreationDateTime = new DateTime(2020, 10, 17, 1, 25, 41, 24, DateTimeKind.Local).AddTicks(9079),
                            EposidesNumber = 6,
                            SeriesId = 885,
                            Title = "magenta XSS Dynamic Phased"
                        },
                        new
                        {
                            Id = 12,
                            CreationDateTime = new DateTime(2020, 12, 20, 2, 46, 15, 419, DateTimeKind.Local).AddTicks(3215),
                            EposidesNumber = 6,
                            SeriesId = 302,
                            Title = "AI Bedfordshire Architect Unbranded"
                        },
                        new
                        {
                            Id = 13,
                            CreationDateTime = new DateTime(2020, 6, 27, 11, 1, 58, 493, DateTimeKind.Local).AddTicks(2075),
                            EposidesNumber = 6,
                            SeriesId = 814,
                            Title = "Baby & Sports Buckinghamshire Sleek Product"
                        },
                        new
                        {
                            Id = 14,
                            CreationDateTime = new DateTime(2021, 4, 12, 20, 6, 38, 495, DateTimeKind.Local).AddTicks(5705),
                            EposidesNumber = 6,
                            SeriesId = 125,
                            Title = "program blue Handmade Fresh Soap parsing"
                        },
                        new
                        {
                            Id = 15,
                            CreationDateTime = new DateTime(2020, 6, 19, 5, 33, 10, 386, DateTimeKind.Local).AddTicks(7002),
                            EposidesNumber = 6,
                            SeriesId = 410,
                            Title = "withdrawal green synthesizing Strategist"
                        },
                        new
                        {
                            Id = 16,
                            CreationDateTime = new DateTime(2020, 7, 1, 14, 58, 52, 102, DateTimeKind.Local).AddTicks(8112),
                            EposidesNumber = 6,
                            SeriesId = 832,
                            Title = "wireless Small Cotton Keyboard Roads Metical"
                        },
                        new
                        {
                            Id = 17,
                            CreationDateTime = new DateTime(2020, 11, 22, 9, 27, 5, 119, DateTimeKind.Local).AddTicks(4910),
                            EposidesNumber = 6,
                            SeriesId = 191,
                            Title = "Credit Card Account Refined Plastic Pants Kids, Books & Tools Bedfordshire"
                        },
                        new
                        {
                            Id = 18,
                            CreationDateTime = new DateTime(2021, 2, 21, 10, 20, 58, 798, DateTimeKind.Local).AddTicks(7250),
                            EposidesNumber = 6,
                            SeriesId = 169,
                            Title = "Handcrafted Wooden Gloves haptic back up Australia"
                        },
                        new
                        {
                            Id = 19,
                            CreationDateTime = new DateTime(2021, 6, 5, 23, 45, 58, 669, DateTimeKind.Local).AddTicks(3455),
                            EposidesNumber = 6,
                            SeriesId = 584,
                            Title = "driver Plastic Kentucky feed"
                        },
                        new
                        {
                            Id = 20,
                            CreationDateTime = new DateTime(2020, 8, 16, 7, 19, 1, 972, DateTimeKind.Local).AddTicks(7697),
                            EposidesNumber = 6,
                            SeriesId = 561,
                            Title = "Optimization Personal Loan Account Forint copy"
                        },
                        new
                        {
                            Id = 21,
                            CreationDateTime = new DateTime(2020, 8, 13, 17, 53, 48, 198, DateTimeKind.Local).AddTicks(5643),
                            EposidesNumber = 6,
                            SeriesId = 529,
                            Title = "methodical Andorra Illinois Sports & Toys"
                        },
                        new
                        {
                            Id = 22,
                            CreationDateTime = new DateTime(2020, 12, 1, 4, 13, 10, 479, DateTimeKind.Local).AddTicks(2937),
                            EposidesNumber = 6,
                            SeriesId = 467,
                            Title = "Steel neural-net Saint Barthelemy hacking"
                        },
                        new
                        {
                            Id = 23,
                            CreationDateTime = new DateTime(2021, 4, 2, 12, 24, 6, 419, DateTimeKind.Local).AddTicks(9647),
                            EposidesNumber = 6,
                            SeriesId = 263,
                            Title = "Program calculate Uzbekistan Sum indexing"
                        },
                        new
                        {
                            Id = 24,
                            CreationDateTime = new DateTime(2020, 6, 11, 14, 47, 5, 982, DateTimeKind.Local).AddTicks(5716),
                            EposidesNumber = 6,
                            SeriesId = 825,
                            Title = "Berkshire Rustic Granite Computer card firmware"
                        },
                        new
                        {
                            Id = 25,
                            CreationDateTime = new DateTime(2021, 1, 12, 21, 11, 59, 588, DateTimeKind.Local).AddTicks(1655),
                            EposidesNumber = 6,
                            SeriesId = 499,
                            Title = "Avon incubate Netherlands Antillian Guilder backing up"
                        },
                        new
                        {
                            Id = 26,
                            CreationDateTime = new DateTime(2021, 1, 13, 9, 3, 21, 433, DateTimeKind.Local).AddTicks(2608),
                            EposidesNumber = 6,
                            SeriesId = 563,
                            Title = "bricks-and-clicks Investment Account uniform Florida"
                        },
                        new
                        {
                            Id = 27,
                            CreationDateTime = new DateTime(2020, 8, 6, 6, 16, 50, 12, DateTimeKind.Local).AddTicks(157),
                            EposidesNumber = 6,
                            SeriesId = 527,
                            Title = "virtual enterprise Games synergies"
                        },
                        new
                        {
                            Id = 28,
                            CreationDateTime = new DateTime(2020, 10, 29, 4, 37, 19, 880, DateTimeKind.Local).AddTicks(1315),
                            EposidesNumber = 6,
                            SeriesId = 811,
                            Title = "Metal Planner Money Market Account Wooden"
                        },
                        new
                        {
                            Id = 29,
                            CreationDateTime = new DateTime(2021, 1, 6, 17, 12, 59, 95, DateTimeKind.Local).AddTicks(1917),
                            EposidesNumber = 6,
                            SeriesId = 765,
                            Title = "Public-key Small initiative Jewelery, Shoes & Games"
                        },
                        new
                        {
                            Id = 30,
                            CreationDateTime = new DateTime(2020, 6, 19, 23, 43, 48, 298, DateTimeKind.Local).AddTicks(8166),
                            EposidesNumber = 6,
                            SeriesId = 20,
                            Title = "deposit bluetooth Nebraska navigating"
                        },
                        new
                        {
                            Id = 31,
                            CreationDateTime = new DateTime(2020, 10, 13, 16, 13, 39, 890, DateTimeKind.Local).AddTicks(8087),
                            EposidesNumber = 6,
                            SeriesId = 98,
                            Title = "Hawaii Automotive, Kids & Baby Wells transmit"
                        },
                        new
                        {
                            Id = 32,
                            CreationDateTime = new DateTime(2021, 2, 19, 21, 17, 1, 279, DateTimeKind.Local).AddTicks(6064),
                            EposidesNumber = 6,
                            SeriesId = 276,
                            Title = "Reverse-engineered Qatari Rial Awesome Concrete Cheese Iraqi Dinar"
                        },
                        new
                        {
                            Id = 33,
                            CreationDateTime = new DateTime(2020, 11, 30, 1, 34, 39, 338, DateTimeKind.Local).AddTicks(1586),
                            EposidesNumber = 6,
                            SeriesId = 717,
                            Title = "applications payment Personal Loan Account teal"
                        },
                        new
                        {
                            Id = 34,
                            CreationDateTime = new DateTime(2020, 10, 22, 12, 46, 57, 541, DateTimeKind.Local).AddTicks(9614),
                            EposidesNumber = 6,
                            SeriesId = 14,
                            Title = "open-source primary purple capacity"
                        },
                        new
                        {
                            Id = 35,
                            CreationDateTime = new DateTime(2021, 4, 1, 21, 8, 13, 783, DateTimeKind.Local).AddTicks(9146),
                            EposidesNumber = 6,
                            SeriesId = 819,
                            Title = "Missouri Utah IB Peso Uruguayo"
                        },
                        new
                        {
                            Id = 36,
                            CreationDateTime = new DateTime(2020, 7, 2, 8, 27, 19, 38, DateTimeKind.Local).AddTicks(8161),
                            EposidesNumber = 6,
                            SeriesId = 887,
                            Title = "IB navigate Buckinghamshire Garden, Jewelery & Kids"
                        },
                        new
                        {
                            Id = 37,
                            CreationDateTime = new DateTime(2020, 9, 15, 20, 5, 14, 421, DateTimeKind.Local).AddTicks(2476),
                            EposidesNumber = 6,
                            SeriesId = 646,
                            Title = "capacitor metrics Fantastic Steel Shoes Guinea"
                        },
                        new
                        {
                            Id = 38,
                            CreationDateTime = new DateTime(2020, 10, 14, 12, 12, 34, 76, DateTimeKind.Local).AddTicks(6569),
                            EposidesNumber = 6,
                            SeriesId = 529,
                            Title = "Response synthesize copy 24/365"
                        },
                        new
                        {
                            Id = 39,
                            CreationDateTime = new DateTime(2021, 5, 28, 9, 36, 51, 535, DateTimeKind.Local).AddTicks(8210),
                            EposidesNumber = 6,
                            SeriesId = 229,
                            Title = "Analyst Plains orchestrate Squares"
                        },
                        new
                        {
                            Id = 40,
                            CreationDateTime = new DateTime(2020, 9, 19, 21, 10, 54, 177, DateTimeKind.Local).AddTicks(829),
                            EposidesNumber = 6,
                            SeriesId = 778,
                            Title = "Ouguiya programming Bridge Investment Account"
                        },
                        new
                        {
                            Id = 41,
                            CreationDateTime = new DateTime(2020, 12, 8, 13, 42, 24, 310, DateTimeKind.Local).AddTicks(1610),
                            EposidesNumber = 6,
                            SeriesId = 578,
                            Title = "web-enabled Metal Nebraska De-engineered"
                        },
                        new
                        {
                            Id = 42,
                            CreationDateTime = new DateTime(2020, 7, 19, 11, 12, 36, 950, DateTimeKind.Local).AddTicks(7133),
                            EposidesNumber = 6,
                            SeriesId = 983,
                            Title = "Networked paradigms Agent content"
                        },
                        new
                        {
                            Id = 43,
                            CreationDateTime = new DateTime(2020, 10, 27, 17, 40, 0, 119, DateTimeKind.Local).AddTicks(9712),
                            EposidesNumber = 6,
                            SeriesId = 886,
                            Title = "Music, Kids & Movies content AGP calculate"
                        },
                        new
                        {
                            Id = 44,
                            CreationDateTime = new DateTime(2021, 3, 20, 11, 7, 50, 485, DateTimeKind.Local).AddTicks(2489),
                            EposidesNumber = 6,
                            SeriesId = 290,
                            Title = "virtual India primary programming"
                        },
                        new
                        {
                            Id = 45,
                            CreationDateTime = new DateTime(2020, 12, 14, 8, 12, 29, 815, DateTimeKind.Local).AddTicks(5778),
                            EposidesNumber = 6,
                            SeriesId = 190,
                            Title = "application purple reboot Namibia"
                        },
                        new
                        {
                            Id = 46,
                            CreationDateTime = new DateTime(2020, 8, 3, 21, 6, 31, 351, DateTimeKind.Local).AddTicks(1104),
                            EposidesNumber = 6,
                            SeriesId = 815,
                            Title = "SMS Hill Montserrat Ergonomic Cotton Salad"
                        },
                        new
                        {
                            Id = 47,
                            CreationDateTime = new DateTime(2020, 6, 20, 3, 4, 39, 225, DateTimeKind.Local).AddTicks(1183),
                            EposidesNumber = 6,
                            SeriesId = 128,
                            Title = "transition Shore Borders Isle"
                        },
                        new
                        {
                            Id = 48,
                            CreationDateTime = new DateTime(2021, 4, 14, 23, 23, 17, 401, DateTimeKind.Local).AddTicks(8444),
                            EposidesNumber = 6,
                            SeriesId = 748,
                            Title = "firewall applications AGP invoice"
                        },
                        new
                        {
                            Id = 49,
                            CreationDateTime = new DateTime(2020, 9, 8, 11, 52, 13, 132, DateTimeKind.Local).AddTicks(7089),
                            EposidesNumber = 6,
                            SeriesId = 905,
                            Title = "Keys bandwidth Yuan Renminbi Dynamic"
                        },
                        new
                        {
                            Id = 50,
                            CreationDateTime = new DateTime(2021, 6, 2, 9, 24, 36, 617, DateTimeKind.Local).AddTicks(3193),
                            EposidesNumber = 6,
                            SeriesId = 443,
                            Title = "Massachusetts e-business Harbor Alaska"
                        });
                });

            modelBuilder.Entity("MoviesApis.Models.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastUpdateDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Serieses");
                });

            modelBuilder.Entity("MoviesApis.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastUpdateDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MoviesApis.Models.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("Duration")
                        .HasColumnType("float");

                    b.Property<DateTime?>("LastUpdateDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.Property<string>("StoragePath")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("MoviesApis.Models.Season", b =>
                {
                    b.HasOne("MoviesApis.Models.Series", "Series")
                        .WithMany("Seasons")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("MoviesApis.Models.Video", b =>
                {
                    b.HasOne("MoviesApis.Models.Season", "Season")
                        .WithMany("Episodes")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("MoviesApis.Models.Season", b =>
                {
                    b.Navigation("Episodes");
                });

            modelBuilder.Entity("MoviesApis.Models.Series", b =>
                {
                    b.Navigation("Seasons");
                });
#pragma warning restore 612, 618
        }
    }
}
