// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoviesApis.DBContexts;

namespace MoviesApis.Migrations
{
    [DbContext(typeof(MySqlDbContext))]
    [Migration("20210609082430_SeedUsers")]
    partial class SeedUsers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("MoviesApis.Models.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EposidesNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdateDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SeriesId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("MoviesApis.Models.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastUpdateDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Serieses");
                });

            modelBuilder.Entity("MoviesApis.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastUpdateDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDateTime = new DateTime(2021, 4, 6, 22, 36, 1, 793, DateTimeKind.Local).AddTicks(9123),
                            FirstName = "Nels",
                            LastName = "Price",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 2,
                            CreationDateTime = new DateTime(2020, 12, 26, 10, 45, 59, 497, DateTimeKind.Local).AddTicks(9983),
                            FirstName = "Eleanora",
                            LastName = "Sauer",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 3,
                            CreationDateTime = new DateTime(2020, 7, 25, 13, 29, 13, 53, DateTimeKind.Local).AddTicks(9392),
                            FirstName = "Nina",
                            LastName = "Ward",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 4,
                            CreationDateTime = new DateTime(2020, 6, 10, 6, 13, 39, 942, DateTimeKind.Local).AddTicks(4074),
                            FirstName = "Hortense",
                            LastName = "Sipes",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 5,
                            CreationDateTime = new DateTime(2020, 9, 14, 17, 35, 36, 936, DateTimeKind.Local).AddTicks(4649),
                            FirstName = "Hanna",
                            LastName = "Marvin",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 6,
                            CreationDateTime = new DateTime(2020, 11, 3, 15, 39, 48, 609, DateTimeKind.Local).AddTicks(8464),
                            FirstName = "Harrison",
                            LastName = "Koepp",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 7,
                            CreationDateTime = new DateTime(2021, 4, 3, 20, 33, 42, 177, DateTimeKind.Local).AddTicks(3777),
                            FirstName = "Kailyn",
                            LastName = "Lueilwitz",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 8,
                            CreationDateTime = new DateTime(2020, 11, 8, 19, 36, 31, 516, DateTimeKind.Local).AddTicks(1228),
                            FirstName = "Reilly",
                            LastName = "Mueller",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 9,
                            CreationDateTime = new DateTime(2021, 2, 26, 4, 18, 22, 124, DateTimeKind.Local).AddTicks(5023),
                            FirstName = "Abigail",
                            LastName = "Goyette",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 10,
                            CreationDateTime = new DateTime(2020, 10, 1, 20, 8, 59, 405, DateTimeKind.Local).AddTicks(2196),
                            FirstName = "Wendy",
                            LastName = "McGlynn",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 11,
                            CreationDateTime = new DateTime(2021, 1, 31, 14, 57, 53, 246, DateTimeKind.Local).AddTicks(1892),
                            FirstName = "Trenton",
                            LastName = "Walsh",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 12,
                            CreationDateTime = new DateTime(2020, 12, 18, 9, 48, 7, 776, DateTimeKind.Local).AddTicks(2003),
                            FirstName = "Virginia",
                            LastName = "Witting",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 13,
                            CreationDateTime = new DateTime(2021, 5, 30, 0, 53, 24, 529, DateTimeKind.Local).AddTicks(5283),
                            FirstName = "Cesar",
                            LastName = "Beier",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 14,
                            CreationDateTime = new DateTime(2020, 6, 12, 17, 46, 42, 656, DateTimeKind.Local).AddTicks(7967),
                            FirstName = "Aidan",
                            LastName = "Auer",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 15,
                            CreationDateTime = new DateTime(2021, 1, 31, 15, 32, 20, 246, DateTimeKind.Local).AddTicks(6530),
                            FirstName = "Emmanuel",
                            LastName = "Kiehn",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 16,
                            CreationDateTime = new DateTime(2020, 8, 22, 4, 36, 45, 887, DateTimeKind.Local).AddTicks(4269),
                            FirstName = "Kathryn",
                            LastName = "Leuschke",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 17,
                            CreationDateTime = new DateTime(2020, 8, 17, 1, 52, 3, 262, DateTimeKind.Local).AddTicks(4924),
                            FirstName = "Alec",
                            LastName = "O'Keefe",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 18,
                            CreationDateTime = new DateTime(2020, 10, 8, 15, 52, 32, 996, DateTimeKind.Local).AddTicks(4674),
                            FirstName = "Martine",
                            LastName = "Strosin",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 19,
                            CreationDateTime = new DateTime(2021, 5, 13, 2, 51, 17, 859, DateTimeKind.Local).AddTicks(2699),
                            FirstName = "Cali",
                            LastName = "Walter",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 20,
                            CreationDateTime = new DateTime(2020, 12, 8, 17, 25, 19, 53, DateTimeKind.Local).AddTicks(9108),
                            FirstName = "Lane",
                            LastName = "Greenfelder",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 21,
                            CreationDateTime = new DateTime(2021, 2, 3, 23, 2, 19, 783, DateTimeKind.Local).AddTicks(5514),
                            FirstName = "Cayla",
                            LastName = "Sawayn",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 22,
                            CreationDateTime = new DateTime(2020, 7, 14, 3, 36, 45, 774, DateTimeKind.Local).AddTicks(9164),
                            FirstName = "Cicero",
                            LastName = "Kuphal",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 23,
                            CreationDateTime = new DateTime(2020, 11, 1, 15, 35, 21, 263, DateTimeKind.Local).AddTicks(649),
                            FirstName = "Lukas",
                            LastName = "Kilback",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 24,
                            CreationDateTime = new DateTime(2021, 1, 13, 12, 26, 34, 173, DateTimeKind.Local).AddTicks(9870),
                            FirstName = "Destini",
                            LastName = "Flatley",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 25,
                            CreationDateTime = new DateTime(2020, 11, 26, 11, 34, 47, 929, DateTimeKind.Local).AddTicks(5601),
                            FirstName = "Kenyon",
                            LastName = "Leannon",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 26,
                            CreationDateTime = new DateTime(2021, 4, 3, 21, 55, 33, 930, DateTimeKind.Local).AddTicks(2907),
                            FirstName = "Claude",
                            LastName = "Kuvalis",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 27,
                            CreationDateTime = new DateTime(2020, 9, 11, 4, 37, 9, 180, DateTimeKind.Local).AddTicks(6196),
                            FirstName = "Daphney",
                            LastName = "Kling",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 28,
                            CreationDateTime = new DateTime(2020, 7, 4, 4, 29, 20, 609, DateTimeKind.Local).AddTicks(1533),
                            FirstName = "Jazmyn",
                            LastName = "Wiegand",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 29,
                            CreationDateTime = new DateTime(2021, 5, 20, 7, 18, 19, 680, DateTimeKind.Local).AddTicks(6987),
                            FirstName = "Scotty",
                            LastName = "Friesen",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 30,
                            CreationDateTime = new DateTime(2021, 5, 24, 5, 39, 14, 370, DateTimeKind.Local).AddTicks(8409),
                            FirstName = "Marlen",
                            LastName = "Schumm",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 31,
                            CreationDateTime = new DateTime(2020, 9, 1, 9, 14, 50, 689, DateTimeKind.Local).AddTicks(1343),
                            FirstName = "Grayson",
                            LastName = "McClure",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 32,
                            CreationDateTime = new DateTime(2021, 3, 15, 7, 50, 34, 38, DateTimeKind.Local).AddTicks(2267),
                            FirstName = "Juliet",
                            LastName = "Stanton",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 33,
                            CreationDateTime = new DateTime(2020, 6, 29, 19, 30, 39, 412, DateTimeKind.Local).AddTicks(179),
                            FirstName = "Luther",
                            LastName = "Cole",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 34,
                            CreationDateTime = new DateTime(2021, 5, 7, 1, 49, 23, 382, DateTimeKind.Local).AddTicks(8395),
                            FirstName = "Isai",
                            LastName = "Ullrich",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 35,
                            CreationDateTime = new DateTime(2021, 1, 10, 1, 56, 11, 61, DateTimeKind.Local).AddTicks(7405),
                            FirstName = "Cletus",
                            LastName = "Runolfsson",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 36,
                            CreationDateTime = new DateTime(2021, 1, 31, 20, 21, 17, 542, DateTimeKind.Local).AddTicks(5174),
                            FirstName = "Haleigh",
                            LastName = "Cartwright",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 37,
                            CreationDateTime = new DateTime(2021, 1, 5, 2, 26, 46, 55, DateTimeKind.Local).AddTicks(4125),
                            FirstName = "Brett",
                            LastName = "Will",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 38,
                            CreationDateTime = new DateTime(2020, 8, 8, 3, 48, 29, 983, DateTimeKind.Local).AddTicks(5580),
                            FirstName = "Sincere",
                            LastName = "Hettinger",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 39,
                            CreationDateTime = new DateTime(2020, 8, 9, 6, 3, 24, 483, DateTimeKind.Local).AddTicks(3316),
                            FirstName = "Nikko",
                            LastName = "Paucek",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 40,
                            CreationDateTime = new DateTime(2021, 3, 10, 14, 4, 55, 656, DateTimeKind.Local).AddTicks(7137),
                            FirstName = "Hanna",
                            LastName = "Hahn",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 41,
                            CreationDateTime = new DateTime(2020, 10, 23, 7, 24, 39, 727, DateTimeKind.Local).AddTicks(8650),
                            FirstName = "Ross",
                            LastName = "Williamson",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 42,
                            CreationDateTime = new DateTime(2020, 10, 11, 10, 7, 22, 350, DateTimeKind.Local).AddTicks(5971),
                            FirstName = "Keanu",
                            LastName = "Stokes",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 43,
                            CreationDateTime = new DateTime(2020, 10, 8, 7, 20, 28, 372, DateTimeKind.Local).AddTicks(1603),
                            FirstName = "Lonzo",
                            LastName = "Bauch",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 44,
                            CreationDateTime = new DateTime(2021, 1, 25, 10, 21, 32, 629, DateTimeKind.Local).AddTicks(9556),
                            FirstName = "Eliane",
                            LastName = "Little",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 45,
                            CreationDateTime = new DateTime(2020, 11, 21, 16, 26, 16, 103, DateTimeKind.Local).AddTicks(1028),
                            FirstName = "Davin",
                            LastName = "Sauer",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 46,
                            CreationDateTime = new DateTime(2021, 4, 3, 18, 26, 25, 664, DateTimeKind.Local).AddTicks(429),
                            FirstName = "Maci",
                            LastName = "Green",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 47,
                            CreationDateTime = new DateTime(2021, 4, 24, 1, 27, 13, 235, DateTimeKind.Local).AddTicks(4203),
                            FirstName = "Josie",
                            LastName = "Konopelski",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 48,
                            CreationDateTime = new DateTime(2020, 7, 30, 10, 2, 22, 193, DateTimeKind.Local).AddTicks(1516),
                            FirstName = "Maynard",
                            LastName = "Lubowitz",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 49,
                            CreationDateTime = new DateTime(2021, 3, 21, 9, 29, 7, 240, DateTimeKind.Local).AddTicks(4647),
                            FirstName = "Libbie",
                            LastName = "Lakin",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 50,
                            CreationDateTime = new DateTime(2021, 4, 10, 5, 3, 39, 407, DateTimeKind.Local).AddTicks(9225),
                            FirstName = "Toy",
                            LastName = "Russel",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 51,
                            CreationDateTime = new DateTime(2020, 8, 14, 5, 7, 54, 591, DateTimeKind.Local).AddTicks(1306),
                            FirstName = "Griffin",
                            LastName = "Feil",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 52,
                            CreationDateTime = new DateTime(2020, 6, 29, 1, 21, 50, 846, DateTimeKind.Local).AddTicks(280),
                            FirstName = "Maudie",
                            LastName = "Metz",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 53,
                            CreationDateTime = new DateTime(2020, 7, 13, 13, 55, 49, 971, DateTimeKind.Local).AddTicks(3010),
                            FirstName = "Jalyn",
                            LastName = "Nienow",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 54,
                            CreationDateTime = new DateTime(2021, 5, 11, 1, 26, 15, 239, DateTimeKind.Local).AddTicks(6082),
                            FirstName = "Newell",
                            LastName = "Sanford",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 55,
                            CreationDateTime = new DateTime(2021, 1, 9, 19, 26, 27, 501, DateTimeKind.Local).AddTicks(4122),
                            FirstName = "Marjory",
                            LastName = "Smith",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 56,
                            CreationDateTime = new DateTime(2020, 11, 9, 18, 11, 11, 971, DateTimeKind.Local).AddTicks(5689),
                            FirstName = "Ana",
                            LastName = "O'Keefe",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 57,
                            CreationDateTime = new DateTime(2021, 1, 16, 7, 30, 19, 284, DateTimeKind.Local).AddTicks(850),
                            FirstName = "Edyth",
                            LastName = "Braun",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 58,
                            CreationDateTime = new DateTime(2020, 8, 4, 5, 36, 20, 212, DateTimeKind.Local).AddTicks(1464),
                            FirstName = "Mable",
                            LastName = "Toy",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 59,
                            CreationDateTime = new DateTime(2021, 1, 11, 8, 47, 21, 24, DateTimeKind.Local).AddTicks(589),
                            FirstName = "Bonita",
                            LastName = "Corkery",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 60,
                            CreationDateTime = new DateTime(2021, 1, 31, 10, 14, 3, 15, DateTimeKind.Local).AddTicks(7625),
                            FirstName = "Oceane",
                            LastName = "Weimann",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 61,
                            CreationDateTime = new DateTime(2021, 3, 3, 0, 2, 52, 762, DateTimeKind.Local).AddTicks(7472),
                            FirstName = "Ike",
                            LastName = "Price",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 62,
                            CreationDateTime = new DateTime(2021, 2, 16, 19, 15, 42, 708, DateTimeKind.Local).AddTicks(8629),
                            FirstName = "Joanie",
                            LastName = "Tremblay",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 63,
                            CreationDateTime = new DateTime(2021, 4, 3, 11, 55, 58, 180, DateTimeKind.Local).AddTicks(5892),
                            FirstName = "Kathleen",
                            LastName = "Littel",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 64,
                            CreationDateTime = new DateTime(2020, 10, 14, 18, 59, 23, 640, DateTimeKind.Local).AddTicks(9514),
                            FirstName = "Lazaro",
                            LastName = "Dibbert",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 65,
                            CreationDateTime = new DateTime(2020, 10, 1, 6, 2, 11, 210, DateTimeKind.Local).AddTicks(9471),
                            FirstName = "Douglas",
                            LastName = "Runte",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 66,
                            CreationDateTime = new DateTime(2020, 9, 21, 5, 38, 33, 767, DateTimeKind.Local).AddTicks(6204),
                            FirstName = "Alycia",
                            LastName = "Aufderhar",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 67,
                            CreationDateTime = new DateTime(2020, 8, 2, 10, 54, 46, 337, DateTimeKind.Local).AddTicks(6253),
                            FirstName = "Isai",
                            LastName = "Maggio",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 68,
                            CreationDateTime = new DateTime(2020, 10, 9, 20, 4, 1, 287, DateTimeKind.Local).AddTicks(1970),
                            FirstName = "Lucas",
                            LastName = "Nolan",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 69,
                            CreationDateTime = new DateTime(2021, 2, 3, 19, 36, 3, 832, DateTimeKind.Local).AddTicks(2482),
                            FirstName = "Okey",
                            LastName = "Rolfson",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 70,
                            CreationDateTime = new DateTime(2020, 12, 26, 17, 40, 14, 181, DateTimeKind.Local).AddTicks(8712),
                            FirstName = "Warren",
                            LastName = "Marvin",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 71,
                            CreationDateTime = new DateTime(2020, 9, 27, 7, 46, 8, 915, DateTimeKind.Local).AddTicks(7329),
                            FirstName = "Kaleb",
                            LastName = "Predovic",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 72,
                            CreationDateTime = new DateTime(2021, 5, 11, 23, 52, 52, 584, DateTimeKind.Local).AddTicks(7716),
                            FirstName = "Kattie",
                            LastName = "Hagenes",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 73,
                            CreationDateTime = new DateTime(2020, 7, 1, 10, 0, 56, 599, DateTimeKind.Local).AddTicks(5322),
                            FirstName = "Ramona",
                            LastName = "Daugherty",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 74,
                            CreationDateTime = new DateTime(2021, 4, 29, 16, 56, 8, 408, DateTimeKind.Local).AddTicks(1359),
                            FirstName = "Beaulah",
                            LastName = "Lakin",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 75,
                            CreationDateTime = new DateTime(2020, 7, 9, 13, 1, 51, 693, DateTimeKind.Local).AddTicks(1058),
                            FirstName = "Grace",
                            LastName = "Pfeffer",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 76,
                            CreationDateTime = new DateTime(2021, 4, 25, 16, 39, 58, 551, DateTimeKind.Local).AddTicks(1177),
                            FirstName = "Natalia",
                            LastName = "Hirthe",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 77,
                            CreationDateTime = new DateTime(2021, 4, 23, 22, 49, 40, 748, DateTimeKind.Local).AddTicks(6155),
                            FirstName = "Carmelo",
                            LastName = "Blanda",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 78,
                            CreationDateTime = new DateTime(2021, 1, 23, 7, 0, 53, 447, DateTimeKind.Local).AddTicks(2283),
                            FirstName = "Matilda",
                            LastName = "Hammes",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 79,
                            CreationDateTime = new DateTime(2021, 5, 20, 15, 5, 45, 714, DateTimeKind.Local).AddTicks(5511),
                            FirstName = "Jewel",
                            LastName = "Schmitt",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 80,
                            CreationDateTime = new DateTime(2021, 4, 17, 23, 11, 23, 361, DateTimeKind.Local).AddTicks(2294),
                            FirstName = "Lelah",
                            LastName = "Rice",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 81,
                            CreationDateTime = new DateTime(2020, 6, 20, 15, 35, 39, 189, DateTimeKind.Local).AddTicks(3572),
                            FirstName = "Violet",
                            LastName = "Mayert",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 82,
                            CreationDateTime = new DateTime(2020, 12, 11, 22, 45, 5, 782, DateTimeKind.Local).AddTicks(9447),
                            FirstName = "Moses",
                            LastName = "Berge",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 83,
                            CreationDateTime = new DateTime(2020, 12, 24, 6, 58, 16, 995, DateTimeKind.Local).AddTicks(6607),
                            FirstName = "Vanessa",
                            LastName = "Reilly",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 84,
                            CreationDateTime = new DateTime(2020, 8, 6, 22, 36, 42, 522, DateTimeKind.Local).AddTicks(1088),
                            FirstName = "Leonel",
                            LastName = "Feil",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 85,
                            CreationDateTime = new DateTime(2021, 5, 19, 11, 40, 9, 263, DateTimeKind.Local).AddTicks(7454),
                            FirstName = "Ora",
                            LastName = "Heathcote",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 86,
                            CreationDateTime = new DateTime(2020, 6, 25, 9, 10, 47, 962, DateTimeKind.Local).AddTicks(1582),
                            FirstName = "Nakia",
                            LastName = "Flatley",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 87,
                            CreationDateTime = new DateTime(2021, 1, 22, 18, 28, 17, 369, DateTimeKind.Local).AddTicks(4786),
                            FirstName = "Ned",
                            LastName = "Balistreri",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 88,
                            CreationDateTime = new DateTime(2020, 12, 9, 15, 35, 46, 668, DateTimeKind.Local).AddTicks(9497),
                            FirstName = "Dalton",
                            LastName = "Schulist",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 89,
                            CreationDateTime = new DateTime(2021, 1, 23, 1, 40, 33, 37, DateTimeKind.Local).AddTicks(7092),
                            FirstName = "Enrico",
                            LastName = "Sporer",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 90,
                            CreationDateTime = new DateTime(2020, 12, 5, 17, 14, 43, 520, DateTimeKind.Local).AddTicks(1977),
                            FirstName = "Enola",
                            LastName = "Bechtelar",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 91,
                            CreationDateTime = new DateTime(2020, 12, 28, 17, 25, 1, 126, DateTimeKind.Local).AddTicks(1435),
                            FirstName = "Alberta",
                            LastName = "DuBuque",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 92,
                            CreationDateTime = new DateTime(2020, 7, 5, 16, 34, 1, 487, DateTimeKind.Local).AddTicks(2172),
                            FirstName = "Peter",
                            LastName = "Connelly",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 93,
                            CreationDateTime = new DateTime(2020, 10, 24, 9, 12, 22, 948, DateTimeKind.Local).AddTicks(6991),
                            FirstName = "Bryce",
                            LastName = "O'Reilly",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 94,
                            CreationDateTime = new DateTime(2020, 10, 14, 17, 42, 4, 149, DateTimeKind.Local).AddTicks(7691),
                            FirstName = "Herminia",
                            LastName = "Schiller",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 95,
                            CreationDateTime = new DateTime(2020, 8, 7, 1, 23, 38, 666, DateTimeKind.Local).AddTicks(9578),
                            FirstName = "Malinda",
                            LastName = "Lowe",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 96,
                            CreationDateTime = new DateTime(2020, 6, 18, 3, 45, 42, 704, DateTimeKind.Local).AddTicks(2126),
                            FirstName = "Eduardo",
                            LastName = "Von",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 97,
                            CreationDateTime = new DateTime(2020, 11, 17, 11, 42, 8, 123, DateTimeKind.Local).AddTicks(7511),
                            FirstName = "Emily",
                            LastName = "Rowe",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 98,
                            CreationDateTime = new DateTime(2020, 9, 24, 7, 5, 34, 120, DateTimeKind.Local).AddTicks(1290),
                            FirstName = "Ayana",
                            LastName = "Stiedemann",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 99,
                            CreationDateTime = new DateTime(2020, 9, 3, 17, 9, 8, 42, DateTimeKind.Local).AddTicks(4899),
                            FirstName = "Nyasia",
                            LastName = "Roberts",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        },
                        new
                        {
                            Id = 100,
                            CreationDateTime = new DateTime(2021, 3, 21, 20, 28, 42, 630, DateTimeKind.Local).AddTicks(106),
                            FirstName = "Janie",
                            LastName = "Jast",
                            Password = "25d55ad283aa400af464c76d713c07ad"
                        });
                });

            modelBuilder.Entity("MoviesApis.Models.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("Duration")
                        .HasColumnType("float");

                    b.Property<DateTime?>("LastUpdateDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.Property<string>("StoragePath")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("MoviesApis.Models.Season", b =>
                {
                    b.HasOne("MoviesApis.Models.Series", "Series")
                        .WithMany("Seasons")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("MoviesApis.Models.Video", b =>
                {
                    b.HasOne("MoviesApis.Models.Season", "Season")
                        .WithMany("Episodes")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("MoviesApis.Models.Season", b =>
                {
                    b.Navigation("Episodes");
                });

            modelBuilder.Entity("MoviesApis.Models.Series", b =>
                {
                    b.Navigation("Seasons");
                });
#pragma warning restore 612, 618
        }
    }
}
